/**
 * Unified loader for test photo landmarks data.
 *
 * Loads .landmarks.json files generated by `npm run generate-landmarks`
 * and .json sidecar metadata files from test/fixtures/photos/.
 */

import { readFileSync, readdirSync, existsSync, statSync } from 'fs';
import { join, basename } from 'path';
import type { Landmark, DetectionFrame } from '../../src/services/pose-detection/pose-types';

const PHOTOS_DIR = join(__dirname, '..', 'fixtures', 'photos');

export interface LandmarkData {
  readonly photoId: number;
  readonly filename: string;
  readonly landmarks: readonly Landmark[];
  readonly worldLandmarks: readonly Landmark[];
  readonly frameWidth: number;
  readonly frameHeight: number;
}

export interface PhotoMetadata {
  readonly photoId: number;
  readonly filename: string;
  readonly category: 'good' | 'forward_head' | 'head_tilt' | 'too_close' | 'edge_case';
  readonly expectedViolations: readonly string[];
  readonly lidAngle: number;
  readonly lighting: 'normal' | 'bright' | 'dim' | 'side';
  readonly severity: 'borderline' | 'moderate' | 'severe' | 'combined' | null;
  readonly notes: string;
}

export interface LandmarkWithMetadata {
  readonly landmarkData: LandmarkData;
  readonly metadata: PhotoMetadata;
}

function getSubdirs(): string[] {
  return readdirSync(PHOTOS_DIR).filter((d) => {
    const fullPath = join(PHOTOS_DIR, d);
    return statSync(fullPath).isDirectory();
  });
}

function findLandmarkFile(photoId: number): string | null {
  for (const subdir of getSubdirs()) {
    const filePath = join(PHOTOS_DIR, subdir, `${photoId}.landmarks.json`);
    if (existsSync(filePath)) {
      return filePath;
    }
  }
  return null;
}

function findMetadataFile(photoId: number): string | null {
  for (const subdir of getSubdirs()) {
    const filePath = join(PHOTOS_DIR, subdir, `${photoId}.json`);
    if (existsSync(filePath)) {
      return filePath;
    }
  }
  return null;
}

export function loadLandmarks(photoId: number): LandmarkData {
  const filePath = findLandmarkFile(photoId);
  if (!filePath) {
    throw new Error(
      `Landmarks not found for photo ${photoId}. Run: npm run generate-landmarks`
    );
  }
  return JSON.parse(readFileSync(filePath, 'utf-8')) as LandmarkData;
}

export function loadMetadata(photoId: number): PhotoMetadata {
  const filePath = findMetadataFile(photoId);
  if (!filePath) {
    throw new Error(`Metadata not found for photo ${photoId}`);
  }
  return JSON.parse(readFileSync(filePath, 'utf-8')) as PhotoMetadata;
}

export function loadLandmarksWithMetadata(photoId: number): LandmarkWithMetadata {
  return {
    landmarkData: loadLandmarks(photoId),
    metadata: loadMetadata(photoId),
  };
}

export function loadLandmarksByCategory(
  category: PhotoMetadata['category']
): readonly LandmarkWithMetadata[] {
  const results: LandmarkWithMetadata[] = [];

  for (const subdir of getSubdirs()) {
    const dirPath = join(PHOTOS_DIR, subdir);
    const jsonFiles = readdirSync(dirPath).filter(
      (f) => f.endsWith('.json') && !f.endsWith('.landmarks.json')
    );

    for (const file of jsonFiles) {
      const metadata = JSON.parse(
        readFileSync(join(dirPath, file), 'utf-8')
      ) as PhotoMetadata;

      if (metadata.category !== category) continue;

      const landmarkFile = join(dirPath, `${metadata.photoId}.landmarks.json`);
      if (!existsSync(landmarkFile)) continue;

      const landmarkData = JSON.parse(
        readFileSync(landmarkFile, 'utf-8')
      ) as LandmarkData;

      results.push({ landmarkData, metadata });
    }
  }

  return results.sort((a, b) => a.metadata.photoId - b.metadata.photoId);
}

export function loadAllLandmarks(): readonly LandmarkWithMetadata[] {
  const results: LandmarkWithMetadata[] = [];

  for (const subdir of getSubdirs()) {
    const dirPath = join(PHOTOS_DIR, subdir);
    const jsonFiles = readdirSync(dirPath).filter(
      (f) => f.endsWith('.json') && !f.endsWith('.landmarks.json')
    );

    for (const file of jsonFiles) {
      const metadata = JSON.parse(
        readFileSync(join(dirPath, file), 'utf-8')
      ) as PhotoMetadata;

      const landmarkFile = join(dirPath, `${metadata.photoId}.landmarks.json`);
      if (!existsSync(landmarkFile)) continue;

      const landmarkData = JSON.parse(
        readFileSync(landmarkFile, 'utf-8')
      ) as LandmarkData;

      results.push({ landmarkData, metadata });
    }
  }

  return results.sort((a, b) => a.metadata.photoId - b.metadata.photoId);
}

export function toDetectionFrame(data: LandmarkData, timestamp = 0): DetectionFrame {
  return {
    landmarks: data.landmarks,
    worldLandmarks: data.worldLandmarks,
    timestamp,
    frameWidth: data.frameWidth,
    frameHeight: data.frameHeight,
  };
}
